config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'recipes/search', to: 'recipes#search', as: :recipes_search
  post 'recipes/search', to: 'recipes#search'
  root 'recipes#search'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_save :set_text_search

  LOCALE = 'french'

  scope :with_ingredients, ->(ingredients) {
    if ingredients.present?
      where("text_search @@ to_tsquery('#{LOCALE}', ?)", ingredients.join(' & '))
    else
      []
    end
  }

  private

  # Every time we update the recipe model, we need to reconstruct the tsvector
  # so that we can full text search the ingredients
  def set_text_search
    query = ActiveRecord::Base.sanitize_sql_array(["SELECT to_tsvector('#{LOCALE}', ?)", ingredients.join(' ')])
    self.text_search = ActiveRecord::Base.connection.execute(query).first['to_tsvector']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :validate_ingredients_query, only: [:search]

  def search
    @ingredients = params[:ingredients] || []
    ingredient = params[:ingredient]

    if params[:commit] == t(:remove)
      @ingredients.delete(params[:ingredient_to_remove])
    else
      @ingredients << ingredient if ingredient.present?
    end

    flash.now[:alert] = nil  # Ensure the alert flash is cleared on successful requests
    @recipes = Recipe.with_ingredients(@ingredients)
  end

  private

  # TODO: find all possible ways to break the full text search request
  # Currently, I'm only aware of sentences and the characters "&" "|" that can break it.
  #
  # TODO: This is quite simple right now but it should probably be inside its own validation class
  def validate_ingredients_query
    ingredient = params[:ingredient]
    if not ingredient.nil?
      @ingredients = params[:ingredients] || []

      alerts = []
      alerts << t(:cannot_be_blank) if ingredient.blank?
      alerts << t(:cannot_be_sentence) if ingredient.split(" ").size > 1
      alerts << t(:cannot_already_be_submitted) if @ingredients.include?(ingredient)
      alerts << t(:cannot_contain_invalid_characters) if ingredient.include?("&") || ingredient.include?("|")
      flash.alert = alerts.join(" and ") unless alerts.blank?

      render :search and return if flash.alert
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewPennylane</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div id="alert">
        <%= msg if type == 'alert' %>
      </div>
      <div id="notice">
        <%= msg if type == 'notice' %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/recipes/search.html.erb
<h1>Search Recipes by Ingredients</h1>

<!-- ADD INGREDIENT FORM -->
<%= form_with url: recipes_search_path, method: :post do |form| %>
  <div>
    <%= form.label :ingredient, "Enter Ingredient:" %>
    <%= form.text_field :ingredient %>
  </div>
  <% @ingredients.each do |ingredient| %>
    <%= hidden_field_tag "ingredients[]", ingredient %>
  <% end %>
  <div>
    <%= form.submit "Add Ingredient" %>
  </div>
<% end %>

<!-- SUBMITTED INGREDIENT -->
<h2>Submitted Ingredients:</h2>
<ul id="ingredients-list">
  <% @ingredients.each do |ingredient| %>
    <li>
      <%= ingredient %>
      <%= form_with url: recipes_search_path, method: :post do |form| %>
        <% (@ingredients).each do |ing| %>
          <%= hidden_field_tag "ingredients[]", ing %>
        <% end %>
        <%= hidden_field_tag :ingredient_to_remove, ingredient %>
        <%= form.submit t(:remove), name: 'commit' %>
      <% end %>
    </li>
  <% end %>
</ul>

<!-- RECIPES -->
<% if @recipes.present? %>
  <h2>Matching Recipes (<%= @recipes.count %>):</h2>
  <ul id="recipes-list">
    <% @recipes.each do |recipe| %>
      <li>
        <strong><%= recipe.name %></strong>
        <p><%= recipe.ingredients.join(", ") %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <h2>No Matching Recipes</h2>
<% end %>